name: scan_card_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  cloud_firestore: ^5.3.0
  firebase_auth:   ^5.2.0
  # date_formatter:  ^0.0.4
  fl_chart: ^0.69.0
  firebase_storage: ^12.3.1
  google_mlkit_text_recognition: ^0.13.1
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - images/
