name: scan_card
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_core: ^3.4.1
  cupertino_icons: ^1.0.8
  google_nav_bar:  ^5.0.6
  cloud_firestore: ^5.3.0
  firebase_auth:   ^5.2.0
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.5.0
  feather_icons: ^1.1.0
  ionicons: ^0.2.1
  loading_animation_widget: ^1.3.0
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  pdf: ^3.11.1
  csv: ^6.0.0
  share_plus: ^10.0.3
  printing: ^5.13.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  #contacts_service: ^0.6.3
  flutter_contacts: ^1.1.9+2
  
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.8.0
  

flutter:
  uses-material-design: true


  assets:
    - image/
    # - image/traduction/

  
  generate: true
 
