name: scan_card
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  cupertino_icons: ^1.0.8
  google_nav_bar:  ^5.0.6
  cloud_firestore: ^5.3.0
  firebase_auth:   ^5.2.0
  date_formatter:  ^0.0.4
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.5.0
  feather_icons: ^1.1.0
  ionicons: ^0.2.1
  loading_animation_widget: ^1.3.0
  google_mlkit_text_recognition: ^0.13.1
  permission_handler: ^11.3.1
  google_fonts: ^5.0.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^4.0.0
  

flutter:
  uses-material-design: true


  assets:
    - image/
    # - assets/lang/
