// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCup9vj7KpHDBiV7kp9_LejC3ETWFPgPlo',
    appId: '1:27801613333:web:d8dfcdace3fa239940ca1c',
    messagingSenderId: '27801613333',
    projectId: 'scancard-53ff8',
    authDomain: 'scancard-53ff8.firebaseapp.com',
    storageBucket: 'scancard-53ff8.appspot.com',
    measurementId: 'G-QCP8KQP5PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpiMHyI9IZXhdcDMiHkNCSOCOwzLJ2PtM',
    appId: '1:27801613333:android:cac4499833dca73140ca1c',
    messagingSenderId: '27801613333',
    projectId: 'scancard-53ff8',
    storageBucket: 'scancard-53ff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qxXBbgfhdTw9TwSsx9HGuntgre3d7-Y',
    appId: '1:27801613333:ios:0dee034208920bf840ca1c',
    messagingSenderId: '27801613333',
    projectId: 'scancard-53ff8',
    storageBucket: 'scancard-53ff8.appspot.com',
    iosBundleId: 'com.example.scanCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdO8nPlASxlFZmRIZynXCrEKhhXYm9dJI',
    appId: '1:185971719048:ios:2f05330dc239ba5cdc583d',
    messagingSenderId: '185971719048',
    projectId: 'scancard-e3266',
    storageBucket: 'scancard-e3266.appspot.com',
    iosBundleId: 'com.example.scanCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzhC6lXvwl0za-siMxESOg8GxKN7rW0eQ',
    appId: '1:185971719048:web:589806aa929d0a36dc583d',
    messagingSenderId: '185971719048',
    projectId: 'scancard-e3266',
    authDomain: 'scancard-e3266.firebaseapp.com',
    storageBucket: 'scancard-e3266.appspot.com',
    measurementId: 'G-4FSN7WW61P',
  );
}